### ISSUE TITLE
Bayesian modelling in perception and action - moving towards sense of agency

### ISSUE THREAD

**Issue by MaudOtten** [ohbm/hackathon2024#16]
### Title

Bayesian modelling in perception and action - moving towards sense of agency

### Short description and the goals for the OHBM BrainHack

In this project, we aim to expand on current trends within Bayesian modeling of perception and action. Our goal is to use computational models to investigate classic theories of sense of agency. Using various open-source tools (e.g. BCI Toolbox, see https://github.com/evans1112/bcitoolbox), we will build a model that allows testing of many assumptions that underly classical and contemporary studies of sense of agency. The structure will be accessible and modular, to allow others to test their questions of interest.

### Link to the Project

https://github.com/CoInAct-group/SenseOfBayesiancy

### Image/Logo for the OHBM brainhack website

https://github.com/CoInAct-group/SenseOfBayesiancy/blob/main/CoInActLogo.pdf

### Project lead

Maud Ottenheijm - @MaudOtten (GitHub), @maudottenheijm (Discord)

### Main Hub

Seoul

### Other hubs covered by the leaders

- [x] Seoul
- [ ] Hybrid (Asia / Pacific)
- [ ] Hybrid (Europe / Middle East / Africa)
- [ ] Hybrid (Americas)

### Skills

We welcome anyone with an interest in (and a basic understanding of) Bayesian modeling of perception and action. Being comfortable in Python is helpful, as we will use various Python packages. An tolerance for puns is the only requirement (my sincere apologies).

### Good first issues

- Basic modular framework
- Define translation & computation steps
- Setting appropriate default values
- Easy visualization (1D)

### Short name for the Discord chat channel (~15 chars)

sense-of-bayesiancy

### Please read and follow the OHBM Code of Conduct

- [X] I agree to follow the OHBM Code of Conduct during the hackathon

**Comment by sina-mansour** [comment]
@MaudOtten Many thanks for your hacktrack submission to brainhack 2024, the submission looks good to go and will soon be listed on our website.

We look forward to seeing you in Seoul!
